services:
  db:
    image: postgres:16
    container_name: schnorr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: huongvt
      POSTGRES_PASSWORD: 20225135
      POSTGRES_DB: schnorr_passkey
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
